### PR TITLE
Move tf dep to test

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
`deepchem` can also be used without tensorflow (`Splitter` for example) and a tensorflow dependency can sometime cause conflicts with conda' solver.

Also `tensorflow` is cpu only (for =<1.15), and some people might want to use `tensorflow-gpu`.

Would that be possible to remove tf from the required deps and only use it for testing the package?

**Comment by hadim** [comment]
ping @simonbray @rbharath

**Review by rbharath — APPROVED** [review]
Looks good on my end!

**Comment by hadim** [comment]
LGTM.

**Comment by hadim** [comment]
Also, I took care of https://github.com/deepchem/deepchem/issues/1861 (for this version only ofc)

**Review by simonbray — APPROVED** [review]

**Comment by simonbray** [comment]
Thanks @hadim!

**Pull request merged**
